services:
  web:
    build: .
    entrypoint: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    container_name: web
    environment:
      FLASK_APP: src.run
      LOGLEVEL: 'DEBUG'
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "5000:5000"
    depends_on:
      library_db:
        condition: service_healthy

  library_db:
    image: postgres:15-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always
